import { Bell, Settings, RefreshCw } from "lucide-react";
import { Link } from "react-router-dom";
import { useSensorData } from "../context/SensorContext";
import { Badge } from "./UI";

export default function Topbar() {
  const { backendConnected, operationMode, source, alerts, refresh, snapshot } = useSensorData();
  return <>
    <div className="topbar"><div className="topbar-status"><span className={"status-dot " + (backendConnected ? "connected" : "")} /><span>{backendConnected ? "Local API connected" : "API disconnected"}</span><span className="topbar-divider">/</span><span>CONVEYOR CB-01</span></div><div className="topbar-actions"><Badge status={operationMode === "SIMULATION" ? "SIMULATION" : "UNKNOWN"}>{source === "SIMULATOR" ? "SIMULATION" : "HARDWARE"}</Badge><button aria-label="Refresh monitoring data" onClick={refresh}><RefreshCw size={17} /></button><Link aria-label="View alert history" to="/alerts"><Bell size={18} /><span>{alerts.length}</span></Link><Link aria-label="Open settings" to="/settings"><Settings size={18} /></Link></div></div>
    {operationMode === "SIMULATION" && <div className="simulation-banner" role="status"><strong>SIMULATION · {snapshot?.demoMode}</strong><span>Demo values generated by the backend. Physical sensor and camera status are shown separately.</span></div>}
  </>;
}
